name: 'raku-test-action'
description: 'Test raku modules caching dependencies'
branding:
  icon: 'life-buoy'
  color: 'blue'
inputs:
  coverage:
    description: "Will test coverage or not"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Obtains source
      uses: actions/checkout@v3
    - name: Cache installed distros
      uses: actions/cache@v3
      id: meta6
      with:
        path: ~/.raku/
        key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
    - name: Test and install for more tests
      if: ${{ ! inputs.coverage }}
      uses: docker://ghcr.io/jj/raku-zef-gha
    - name: Test and install for more tests
      if: ${{ inputs.coverage }}
      uses: docker://ghcr.io/jj/raku-racoco-gha

