name: 'raku-test-action'
description: 'Test raku modules caching dependencies'
branding:
  icon: 'life-buoy'
  color: 'blue'
runs:
  using: "docker"
  image: ghcr.io/jj/raku-zef-gha
  steps:
    - name: Cache installed dists
      uses: actions/cache@v2
      id: meta6
      with:
        path: ~/.raku/
        key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
    - name: Install modules
      if: steps.meta6.outputs.cache-hit != 'true'
      run: zef install --deps-only .
    - name: Test and install for more tests
      run: zef install .
